// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Blog → Header*
 */
export interface BlogDocumentDataHeaderItem {
  /**
   * logo field in *Blog → Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.header[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Link Label 1 field in *Blog → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.header[].linklabel1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel1: prismic.KeyTextField;

  /**
   * Link 1 field in *Blog → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.header[].link1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * Link Label 2 field in *Blog → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.header[].linklabel2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel2: prismic.KeyTextField;

  /**
   * Link 2 field in *Blog → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.header[].link2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link2: prismic.KeyTextField;

  /**
   * Link Label 3 field in *Blog → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.header[].linklabel3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel3: prismic.KeyTextField;

  /**
   * Link 3 field in *Blog → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.header[].link3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link3: prismic.KeyTextField;

  /**
   * Link Label 4 field in *Blog → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.header[].linklabel4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel4: prismic.KeyTextField;

  /**
   * Link 4 field in *Blog → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.header[].link4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link4: prismic.KeyTextField;

  /**
   * Link Label 5 field in *Blog → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.header[].linklabel5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel5: prismic.KeyTextField;

  /**
   * Link 5 field in *Blog → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.header[].link5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link5: prismic.KeyTextField;

  /**
   * Ingles? field in *Blog → Header*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog.header[].idioma
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  idioma: prismic.BooleanField;
}

/**
 * Item in *Blog → Rodapé*
 */
export interface BlogDocumentDataRodapeItem {
  /**
   * Titulo field in *Blog → Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.rodape[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Link Label 1 field in *Blog → Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.rodape[].linklabel1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel1: prismic.KeyTextField;

  /**
   * Link 1 field in *Blog → Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.rodape[].link1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * Link Label 2 field in *Blog → Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.rodape[].linklabel2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel2: prismic.KeyTextField;

  /**
   * Link 2 field in *Blog → Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.rodape[].link2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link2: prismic.KeyTextField;

  /**
   * Link Label 3 field in *Blog → Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.rodape[].linklabel3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel3: prismic.KeyTextField;

  /**
   * Link 3 field in *Blog → Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.rodape[].link3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link3: prismic.KeyTextField;
}

type BlogDocumentDataSlicesSlice = EmAltaSlice | GrupoBlogSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Header field in *Blog*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.header[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  header: prismic.GroupField<Simplify<BlogDocumentDataHeaderItem>>;

  /**
   * Rodapé field in *Blog*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.rodape[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rodape: prismic.GroupField<Simplify<BlogDocumentDataRodapeItem>>;

  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

/**
 * Item in *Blog Post → Header*
 */
export interface BlogPostDocumentDataHeaderItem {
  /**
   * logo field in *Blog Post → Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.header[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Link Label 1 field in *Blog Post → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.header[].linklabel1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel1: prismic.KeyTextField;

  /**
   * Link 1 field in *Blog Post → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.header[].link1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * Link Label 2 field in *Blog Post → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.header[].linklabel2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel2: prismic.KeyTextField;

  /**
   * Link 2 field in *Blog Post → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.header[].link2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link2: prismic.KeyTextField;

  /**
   * Link Label 3 field in *Blog Post → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.header[].linklabel3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel3: prismic.KeyTextField;

  /**
   * Link 3 field in *Blog Post → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.header[].link3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link3: prismic.KeyTextField;

  /**
   * Link Label 4 field in *Blog Post → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.header[].linklabel4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel4: prismic.KeyTextField;

  /**
   * Link 4 field in *Blog Post → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.header[].link4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link4: prismic.KeyTextField;

  /**
   * Link Label 5 field in *Blog Post → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.header[].linklabel5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel5: prismic.KeyTextField;

  /**
   * Link 5 field in *Blog Post → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.header[].link5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link5: prismic.KeyTextField;
}

type BlogPostDocumentDataSlicesSlice = BlogConteudoSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Header field in *Blog Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.header[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  header: prismic.GroupField<Simplify<BlogPostDocumentDataHeaderItem>>;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Item in *faqpage → Header*
 */
export interface FaqpageDocumentDataHeaderItem {
  /**
   * logo field in *faqpage → Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.header[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Link Label 1 field in *faqpage → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.header[].linklabel1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel1: prismic.KeyTextField;

  /**
   * Link 1 field in *faqpage → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.header[].link1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * Link Label 2 field in *faqpage → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.header[].linklabel2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel2: prismic.KeyTextField;

  /**
   * Link 2 field in *faqpage → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.header[].link2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link2: prismic.KeyTextField;

  /**
   * Link Label 3 field in *faqpage → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.header[].linklabel3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel3: prismic.KeyTextField;

  /**
   * Link 3 field in *faqpage → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.header[].link3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link3: prismic.KeyTextField;

  /**
   * Botao Label field in *faqpage → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.header[].botaolabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  botaolabel: prismic.KeyTextField;

  /**
   * Link Botao field in *faqpage → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.header[].linkbotao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkbotao: prismic.KeyTextField;

  /**
   * Link Label 4 field in *faqpage → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.header[].linklabel4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel4: prismic.KeyTextField;

  /**
   * Link 4 field in *faqpage → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.header[].link4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link4: prismic.KeyTextField;

  /**
   * idioma field in *faqpage → Header*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: faqpage.header[].idioma
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  idioma: prismic.BooleanField;
}

/**
 * Item in *faqpage → Rodape Menu*
 */
export interface FaqpageDocumentDataRodapemenuItem {
  /**
   * Titulo field in *faqpage → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapemenu[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Link Label 1 field in *faqpage → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapemenu[].linklabel1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel1: prismic.KeyTextField;

  /**
   * Link 1 field in *faqpage → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapemenu[].link1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * Link Label 2 field in *faqpage → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapemenu[].linklabel2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel2: prismic.KeyTextField;

  /**
   * Link 2 field in *faqpage → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapemenu[].link2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link2: prismic.KeyTextField;

  /**
   * Link Label 3 field in *faqpage → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapemenu[].linklabel3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel3: prismic.KeyTextField;

  /**
   * Link 3 field in *faqpage → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapemenu[].link3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link3: prismic.KeyTextField;

  /**
   * Link Label 4 field in *faqpage → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapemenu[].linklabel4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel4: prismic.KeyTextField;

  /**
   * Link 4 field in *faqpage → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapemenu[].link4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link4: prismic.KeyTextField;
}

/**
 * Item in *faqpage → Rodape Conteudos*
 */
export interface FaqpageDocumentDataRodapeconteudosItem {
  /**
   * Titulo field in *faqpage → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapeconteudos[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Link Label 1 field in *faqpage → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapeconteudos[].linklabel1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel1: prismic.KeyTextField;

  /**
   * Link 1 field in *faqpage → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapeconteudos[].link1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * Link Label 2 field in *faqpage → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapeconteudos[].linklabel2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel2: prismic.KeyTextField;

  /**
   * Link 2 field in *faqpage → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapeconteudos[].link2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link2: prismic.KeyTextField;

  /**
   * Link Label 3 field in *faqpage → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapeconteudos[].linklabel3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel3: prismic.KeyTextField;

  /**
   * Link 3 field in *faqpage → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapeconteudos[].link3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link3: prismic.KeyTextField;
}

type FaqpageDocumentDataSlicesSlice = FaqSlice;

/**
 * Content for faqpage documents
 */
interface FaqpageDocumentData {
  /**
   * Header field in *faqpage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.header[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  header: prismic.GroupField<Simplify<FaqpageDocumentDataHeaderItem>>;

  /**
   * Rodape Menu field in *faqpage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapemenu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rodapemenu: prismic.GroupField<Simplify<FaqpageDocumentDataRodapemenuItem>>;

  /**
   * Rodape Conteudos field in *faqpage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.rodapeconteudos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rodapeconteudos: prismic.GroupField<
    Simplify<FaqpageDocumentDataRodapeconteudosItem>
  >;

  /**
   * Slice Zone field in *faqpage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FaqpageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *faqpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: faqpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *faqpage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *faqpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: faqpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * faqpage document from Prismic
 *
 * - **API ID**: `faqpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FaqpageDocumentData>,
    "faqpage",
    Lang
  >;

type IndexDocumentDataSlicesSlice = never;

/**
 * Content for index documents
 */
interface IndexDocumentData {
  /**
   * Slice Zone field in *index*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: index.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<IndexDocumentDataSlicesSlice>
  /**
   * Meta Description field in *index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: index.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: index.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * index document from Prismic
 *
 * - **API ID**: `index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<IndexDocumentData>, "index", Lang>;

/**
 * Item in *Landing Page → Header*
 */
export interface LandingPageDocumentDataHeaderItem {
  /**
   * logo field in *Landing Page → Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Link Label 1 field in *Landing Page → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header[].linklabel1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel1: prismic.KeyTextField;

  /**
   * Link 1 field in *Landing Page → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header[].link1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * Link Label 2 field in *Landing Page → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header[].linklabel2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel2: prismic.KeyTextField;

  /**
   * Link 2 field in *Landing Page → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header[].link2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link2: prismic.KeyTextField;

  /**
   * Link Label 3 field in *Landing Page → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header[].linklabel3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel3: prismic.KeyTextField;

  /**
   * Link 3 field in *Landing Page → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header[].link3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link3: prismic.KeyTextField;

  /**
   * Botao Label field in *Landing Page → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header[].botaolabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  botaolabel: prismic.KeyTextField;

  /**
   * Link Botao field in *Landing Page → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header[].linkbotao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkbotao: prismic.KeyTextField;

  /**
   * Link Label 4 field in *Landing Page → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header[].linklabel4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel4: prismic.KeyTextField;

  /**
   * link 4 field in *Landing Page → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header[].link4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link4: prismic.KeyTextField;

  /**
   * Ingles? field in *Landing Page → Header*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: landing_page.header[].idioma
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  idioma: prismic.BooleanField;
}

/**
 * Item in *Landing Page → Banner*
 */
export interface LandingPageDocumentDataBannerItem {
  /**
   * Texto field in *Landing Page → Banner*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.banner[].texto
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto: prismic.RichTextField;

  /**
   * Imagem Esquerda field in *Landing Page → Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.banner[].img_esq
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img_esq: prismic.ImageField<never>;

  /**
   * Imagem Direita field in *Landing Page → Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.banner[].img_dir
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img_dir: prismic.ImageField<never>;

  /**
   * Imagem Baixo field in *Landing Page → Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.banner[].img_baixo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img_baixo: prismic.ImageField<never>;

  /**
   * Botao Label field in *Landing Page → Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.banner[].botaolabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  botaolabel: prismic.KeyTextField;

  /**
   * Link Botao field in *Landing Page → Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.banner[].linkbotao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkbotao: prismic.KeyTextField;
}

/**
 * Item in *Landing Page → Rodape Menu*
 */
export interface LandingPageDocumentDataRodapemenuItem {
  /**
   * Titulo field in *Landing Page → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapemenu[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Link Label 1 field in *Landing Page → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapemenu[].linklabel1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel1: prismic.KeyTextField;

  /**
   * Link 1 field in *Landing Page → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapemenu[].link1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * Link Label 2 field in *Landing Page → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapemenu[].linklabel2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel2: prismic.KeyTextField;

  /**
   * Link 2 field in *Landing Page → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapemenu[].link2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link2: prismic.KeyTextField;

  /**
   * Link Label 3 field in *Landing Page → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapemenu[].linklabel3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel3: prismic.KeyTextField;

  /**
   * Link 3 field in *Landing Page → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapemenu[].link3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link3: prismic.KeyTextField;

  /**
   * Link Label 4 field in *Landing Page → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapemenu[].linklabel4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel4: prismic.KeyTextField;

  /**
   * Link 4 field in *Landing Page → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapemenu[].link4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link4: prismic.KeyTextField;
}

/**
 * Item in *Landing Page → Rodape Conteudos*
 */
export interface LandingPageDocumentDataRodapeconteudosItem {
  /**
   * Titulo field in *Landing Page → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapeconteudos[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Link Label 1 field in *Landing Page → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapeconteudos[].linklabel1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel1: prismic.KeyTextField;

  /**
   * Link 1 field in *Landing Page → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapeconteudos[].link1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * Link Label 2 field in *Landing Page → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapeconteudos[].linklabel2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel2: prismic.KeyTextField;

  /**
   * Link 2 field in *Landing Page → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapeconteudos[].link2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link2: prismic.KeyTextField;

  /**
   * Link Label 3 field in *Landing Page → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapeconteudos[].linklabel3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel3: prismic.KeyTextField;

  /**
   * Link 3 field in *Landing Page → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapeconteudos[].link3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link3: prismic.KeyTextField;
}

type LandingPageDocumentDataSlicesSlice =
  | MapaSlice
  | CorpoSlice
  | FormularioSlice
  | NewstellerSlice;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
  /**
   * Header field in *Landing Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  header: prismic.GroupField<Simplify<LandingPageDocumentDataHeaderItem>>;

  /**
   * Popup Texto field in *Landing Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.popuptexto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  popuptexto: prismic.RichTextField;

  /**
   * Popup Imagem field in *Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.popupimagem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  popupimagem: prismic.ImageField<never>;

  /**
   * Banner field in *Landing Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.banner[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  banner: prismic.GroupField<Simplify<LandingPageDocumentDataBannerItem>>;

  /**
   * Rodape Menu field in *Landing Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapemenu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rodapemenu: prismic.GroupField<
    Simplify<LandingPageDocumentDataRodapemenuItem>
  >;

  /**
   * Rodape Conteudos field in *Landing Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.rodapeconteudos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rodapeconteudos: prismic.GroupField<
    Simplify<LandingPageDocumentDataRodapeconteudosItem>
  >;

  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Item in *quiz → Header*
 */
export interface QuizDocumentDataHeaderItem {
  /**
   * logo field in *quiz → Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.header[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Link Label 1 field in *quiz → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.header[].linklabel1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel1: prismic.KeyTextField;

  /**
   * Link 1 field in *quiz → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.header[].link1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * Link Label 2 field in *quiz → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.header[].linklabel2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel2: prismic.KeyTextField;

  /**
   * Link 2 field in *quiz → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.header[].link2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link2: prismic.KeyTextField;

  /**
   * Link Label 3 field in *quiz → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.header[].linklabel3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel3: prismic.KeyTextField;

  /**
   * Link 3 field in *quiz → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.header[].link3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link3: prismic.KeyTextField;

  /**
   * Botao Label field in *quiz → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.header[].botaolabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  botaolabel: prismic.KeyTextField;

  /**
   * Link Botao field in *quiz → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.header[].linkbotao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkbotao: prismic.KeyTextField;

  /**
   * Link Label 4 field in *quiz → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.header[].linklabel4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel4: prismic.KeyTextField;

  /**
   * Link 4 field in *quiz → Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.header[].link4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link4: prismic.KeyTextField;

  /**
   * idioma field in *quiz → Header*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: quiz.header[].idioma
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  idioma: prismic.BooleanField;
}

/**
 * Item in *quiz → Rodape Menu*
 */
export interface QuizDocumentDataRodapemenuItem {
  /**
   * Titulo field in *quiz → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapemenu[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Link Label 1 field in *quiz → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapemenu[].linklabel1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel1: prismic.KeyTextField;

  /**
   * Link 1 field in *quiz → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapemenu[].link1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * Link Label 2 field in *quiz → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapemenu[].linklabel2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel2: prismic.KeyTextField;

  /**
   * Link 2 field in *quiz → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapemenu[].link2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link2: prismic.KeyTextField;

  /**
   * Link Label 3 field in *quiz → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapemenu[].linklabel3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel3: prismic.KeyTextField;

  /**
   * Link 3 field in *quiz → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapemenu[].link3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link3: prismic.KeyTextField;

  /**
   * Link Label 4 field in *quiz → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapemenu[].linklabel4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel4: prismic.KeyTextField;

  /**
   * Link 4 field in *quiz → Rodape Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapemenu[].link4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link4: prismic.KeyTextField;
}

/**
 * Item in *quiz → Rodape Conteudos*
 */
export interface QuizDocumentDataRodapeconteudosItem {
  /**
   * Titulo field in *quiz → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapeconteudos[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Link Label 1 field in *quiz → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapeconteudos[].linklabel1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel1: prismic.KeyTextField;

  /**
   * Link 1 field in *quiz → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapeconteudos[].link1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * Link Label 2 field in *quiz → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapeconteudos[].linklabel2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel2: prismic.KeyTextField;

  /**
   * Link 2 field in *quiz → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapeconteudos[].link2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link2: prismic.KeyTextField;

  /**
   * Link Label 3 field in *quiz → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapeconteudos[].linklabel3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel3: prismic.KeyTextField;

  /**
   * Link 3 field in *quiz → Rodape Conteudos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapeconteudos[].link3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link3: prismic.KeyTextField;
}

type QuizDocumentDataSlicesSlice = QuizSliceSlice;

/**
 * Content for quiz documents
 */
interface QuizDocumentData {
  /**
   * Header field in *quiz*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.header[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  header: prismic.GroupField<Simplify<QuizDocumentDataHeaderItem>>;

  /**
   * Rodape Menu field in *quiz*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapemenu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rodapemenu: prismic.GroupField<Simplify<QuizDocumentDataRodapemenuItem>>;

  /**
   * Rodape Conteudos field in *quiz*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.rodapeconteudos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rodapeconteudos: prismic.GroupField<
    Simplify<QuizDocumentDataRodapeconteudosItem>
  >;

  /**
   * Slice Zone field in *quiz*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<QuizDocumentDataSlicesSlice>
  /**
   * Meta Description field in *quiz*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: quiz.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *quiz*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *quiz*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: quiz.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * quiz document from Prismic
 *
 * - **API ID**: `quiz`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type QuizDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<QuizDocumentData>, "quiz", Lang>;

type SurveyDocumentDataSlicesSlice = never;

/**
 * Content for Survey documents
 */
interface SurveyDocumentData {
  /**
   * Slice Zone field in *Survey*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: survey.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SurveyDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Survey*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: survey.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Survey*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: survey.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Survey*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: survey.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Survey document from Prismic
 *
 * - **API ID**: `survey`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SurveyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SurveyDocumentData>, "survey", Lang>;

type TesteDocumentDataSlicesSlice = never;

/**
 * Content for Teste documents
 */
interface TesteDocumentData {
  /**
   * Slice Zone field in *Teste*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: teste.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TesteDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Teste*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: teste.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Teste*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teste.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Teste*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: teste.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Teste document from Prismic
 *
 * - **API ID**: `teste`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TesteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<TesteDocumentData>, "teste", Lang>;

export type AllDocumentTypes =
  | BlogDocument
  | BlogPostDocument
  | FaqpageDocument
  | IndexDocument
  | LandingPageDocument
  | QuizDocument
  | SurveyDocument
  | TesteDocument;

/**
 * Primary content in *Banner → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Fundo field in *Banner → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.fundo
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  fundo: prismic.ColorField;

  /**
   * ImagemEsquerda field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.imagemesquerda
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagemesquerda: prismic.ImageField<never>;

  /**
   * ImagemDireita field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.imagemdireita
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagemdireita: prismic.ImageField<never>;

  /**
   * ImagemBaixo field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.imagembaixo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagembaixo: prismic.ImageField<never>;

  /**
   * Botao field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.botao
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  botao: prismic.RichTextField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *BlogConteudo → Primary*
 */
export interface BlogConteudoSliceDefaultPrimary {
  /**
   * Texto field in *BlogConteudo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_conteudo.primary.texto
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto: prismic.RichTextField;
}

/**
 * Default variation for BlogConteudo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogConteudoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogConteudoSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *BlogConteudo → Primary*
 */
export interface BlogConteudoSliceImagemPrimary {
  /**
   * Imagem field in *BlogConteudo → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_conteudo.primary.imagem
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;
}

/**
 * Imagem variation for BlogConteudo Slice
 *
 * - **API ID**: `imagem`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogConteudoSliceImagem = prismic.SharedSliceVariation<
  "imagem",
  Simplify<BlogConteudoSliceImagemPrimary>,
  never
>;

/**
 * Primary content in *BlogConteudo → Primary*
 */
export interface BlogConteudoSliceIFramePrimary {
  /**
   * Frame field in *BlogConteudo → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_conteudo.primary.frame
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  frame: prismic.EmbedField;
}

/**
 * iFrame variation for BlogConteudo Slice
 *
 * - **API ID**: `iFrame`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogConteudoSliceIFrame = prismic.SharedSliceVariation<
  "iFrame",
  Simplify<BlogConteudoSliceIFramePrimary>,
  never
>;

/**
 * Slice variation for *BlogConteudo*
 */
type BlogConteudoSliceVariation =
  | BlogConteudoSliceDefault
  | BlogConteudoSliceImagem
  | BlogConteudoSliceIFrame;

/**
 * BlogConteudo Shared Slice
 *
 * - **API ID**: `blog_conteudo`
 * - **Description**: BlogConteudo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogConteudoSlice = prismic.SharedSlice<
  "blog_conteudo",
  BlogConteudoSliceVariation
>;

/**
 * Primary content in *Corpo → Items*
 */
export interface CorpoSliceDefaultItem {
  /**
   * Titulo field in *Corpo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Cor field in *Corpo → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].cor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  cor: prismic.ColorField;
}

/**
 * Default variation for Corpo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CorpoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CorpoSliceDefaultItem>
>;

/**
 * Primary content in *Corpo → Items*
 */
export interface CorpoSliceImagensItem {
  /**
   * Titulo field in *Corpo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Cor field in *Corpo → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].cor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  cor: prismic.ColorField;

  /**
   * Imagem 1 field in *Corpo → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].img1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img1: prismic.ImageField<never>;

  /**
   * Imagem 2 field in *Corpo → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].img2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img2: prismic.ImageField<never>;

  /**
   * Imagem 3 field in *Corpo → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].img3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img3: prismic.ImageField<never>;
}

/**
 * Imagens variation for Corpo Slice
 *
 * - **API ID**: `imagens`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CorpoSliceImagens = prismic.SharedSliceVariation<
  "imagens",
  Record<string, never>,
  Simplify<CorpoSliceImagensItem>
>;

/**
 * Primary content in *Corpo → Items*
 */
export interface CorpoSliceIFrameItem {
  /**
   * Titulo field in *Corpo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Cor field in *Corpo → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].cor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  cor: prismic.ColorField;

  /**
   * Incorporado field in *Corpo → Items*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].incorporado
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  incorporado: prismic.EmbedField;
}

/**
 * IFrame variation for Corpo Slice
 *
 * - **API ID**: `iFrame`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CorpoSliceIFrame = prismic.SharedSliceVariation<
  "iFrame",
  Record<string, never>,
  Simplify<CorpoSliceIFrameItem>
>;

/**
 * Primary content in *Corpo → Items*
 */
export interface CorpoSliceLogosItem {
  /**
   * titulologos field in *Corpo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].titulologos
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulologos: prismic.KeyTextField;

  /**
   * logo 1 field in *Corpo → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].logo1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo1: prismic.ImageField<never>;

  /**
   * logo 2 field in *Corpo → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].logo2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo2: prismic.ImageField<never>;

  /**
   * logo 3 field in *Corpo → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].logo3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo3: prismic.ImageField<never>;

  /**
   * logo 4 field in *Corpo → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].logo4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo4: prismic.ImageField<never>;

  /**
   * logo 5 field in *Corpo → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].logo5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo5: prismic.ImageField<never>;
}

/**
 * logos variation for Corpo Slice
 *
 * - **API ID**: `logos`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CorpoSliceLogos = prismic.SharedSliceVariation<
  "logos",
  Record<string, never>,
  Simplify<CorpoSliceLogosItem>
>;

/**
 * Primary content in *Corpo → Items*
 */
export interface CorpoSliceDepoimentosItem {
  /**
   * Depoimento 1 field in *Corpo → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].depoimento_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  depoimento_1: prismic.RichTextField;

  /**
   * Depoimento 2 field in *Corpo → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].depoimento_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  depoimento_2: prismic.RichTextField;

  /**
   * Depoimento 3 field in *Corpo → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].depoimento_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  depoimento_3: prismic.RichTextField;

  /**
   * Nome 1 field in *Corpo → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].nome_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  nome_1: prismic.RichTextField;

  /**
   * Nome 2 field in *Corpo → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].nome_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  nome_2: prismic.RichTextField;

  /**
   * Nome 3 field in *Corpo → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].nome_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  nome_3: prismic.RichTextField;
}

/**
 * depoimentos variation for Corpo Slice
 *
 * - **API ID**: `depoimentos`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CorpoSliceDepoimentos = prismic.SharedSliceVariation<
  "depoimentos",
  Record<string, never>,
  Simplify<CorpoSliceDepoimentosItem>
>;

/**
 * Primary content in *Corpo → Items*
 */
export interface CorpoSliceGatilhossociaisItem {
  /**
   * numero field in *Corpo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].numero
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  numero: prismic.KeyTextField;

  /**
   * frase field in *Corpo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].frase
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  frase: prismic.KeyTextField;
}

/**
 * gatilhos sociais variation for Corpo Slice
 *
 * - **API ID**: `gatilhossociais`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CorpoSliceGatilhossociais = prismic.SharedSliceVariation<
  "gatilhossociais",
  Record<string, never>,
  Simplify<CorpoSliceGatilhossociaisItem>
>;

/**
 * Primary content in *Corpo → Items*
 */
export interface CorpoSliceAgendaItem {
  /**
   * linkAgenda field in *Corpo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].linkagenda
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkagenda: prismic.KeyTextField;
}

/**
 * agenda variation for Corpo Slice
 *
 * - **API ID**: `agenda`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CorpoSliceAgenda = prismic.SharedSliceVariation<
  "agenda",
  Record<string, never>,
  Simplify<CorpoSliceAgendaItem>
>;

/**
 * mapa variation for Corpo Slice
 *
 * - **API ID**: `mapa`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CorpoSliceMapa = prismic.SharedSliceVariation<
  "mapa",
  Record<string, never>,
  never
>;

/**
 * Primary content in *Corpo → Items*
 */
export interface CorpoSliceBotaoQuizItem {
  /**
   * Titulo field in *Corpo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * link field in *Corpo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;

  /**
   * Label field in *Corpo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].labellink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labellink: prismic.KeyTextField;

  /**
   * Cor field in *Corpo → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: corpo.items[].cor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  cor: prismic.ColorField;
}

/**
 * Botao quiz variation for Corpo Slice
 *
 * - **API ID**: `botaoQuiz`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CorpoSliceBotaoQuiz = prismic.SharedSliceVariation<
  "botaoQuiz",
  Record<string, never>,
  Simplify<CorpoSliceBotaoQuizItem>
>;

/**
 * Slice variation for *Corpo*
 */
type CorpoSliceVariation =
  | CorpoSliceDefault
  | CorpoSliceImagens
  | CorpoSliceIFrame
  | CorpoSliceLogos
  | CorpoSliceDepoimentos
  | CorpoSliceGatilhossociais
  | CorpoSliceAgenda
  | CorpoSliceMapa
  | CorpoSliceBotaoQuiz;

/**
 * Corpo Shared Slice
 *
 * - **API ID**: `corpo`
 * - **Description**: Corpo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CorpoSlice = prismic.SharedSlice<"corpo", CorpoSliceVariation>;

/**
 * Primary content in *EmAlta → Primary*
 */
export interface EmAltaSliceDefaultPrimary {
  /**
   * TItulo Grupo field in *EmAlta → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: em_alta.primary.titulogrupo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulogrupo: prismic.KeyTextField;
}

/**
 * Primary content in *EmAlta → Items*
 */
export interface EmAltaSliceDefaultItem {
  /**
   * Titulo Post field in *EmAlta → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: em_alta.items[].titulopost
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulopost: prismic.KeyTextField;

  /**
   * Imagem field in *EmAlta → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: em_alta.items[].imagem
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;

  /**
   * Link field in *EmAlta → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ./blog
   * - **API ID Path**: em_alta.items[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Default variation for EmAlta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmAltaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EmAltaSliceDefaultPrimary>,
  Simplify<EmAltaSliceDefaultItem>
>;

/**
 * Slice variation for *EmAlta*
 */
type EmAltaSliceVariation = EmAltaSliceDefault;

/**
 * EmAlta Shared Slice
 *
 * - **API ID**: `em_alta`
 * - **Description**: EmAlta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmAltaSlice = prismic.SharedSlice<"em_alta", EmAltaSliceVariation>;

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * Pergunta field in *Faq → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].pergunta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pergunta: prismic.KeyTextField;

  /**
   * Resposta field in *Faq → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].resposta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta: prismic.KeyTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * titulo variation for Faq Slice
 *
 * - **API ID**: `titulo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceTitulo = prismic.SharedSliceVariation<
  "titulo",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault | FaqSliceTitulo;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Formulario → Primary*
 */
export interface FormularioSliceDefaultPrimary {
  /**
   * Titulo field in *Formulario → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Cor field in *Formulario → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.primary.cor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  cor: prismic.ColorField;

  /**
   * Ingles? field in *Formulario → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: formulario.primary.ingles
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  ingles: prismic.BooleanField;
}

/**
 * Default variation for Formulario Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormularioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormularioSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Formulario*
 */
type FormularioSliceVariation = FormularioSliceDefault;

/**
 * Formulario Shared Slice
 *
 * - **API ID**: `formulario`
 * - **Description**: Formulario
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormularioSlice = prismic.SharedSlice<
  "formulario",
  FormularioSliceVariation
>;

/**
 * Primary content in *GrupoBlog → Primary*
 */
export interface GrupoBlogSliceDefaultPrimary {
  /**
   * Titulo Grupo field in *GrupoBlog → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grupo_blog.primary.titulogrupo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulogrupo: prismic.KeyTextField;

  /**
   * ID Grupo field in *GrupoBlog → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grupo_blog.primary.idgrupo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  idgrupo: prismic.KeyTextField;
}

/**
 * Primary content in *GrupoBlog → Items*
 */
export interface GrupoBlogSliceDefaultItem {
  /**
   * Titulo Post field in *GrupoBlog → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grupo_blog.items[].titulopost
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulopost: prismic.KeyTextField;

  /**
   * Imagem field in *GrupoBlog → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grupo_blog.items[].imagem
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;

  /**
   * Link field in *GrupoBlog → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ./blog
   * - **API ID Path**: grupo_blog.items[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Default variation for GrupoBlog Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GrupoBlogSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GrupoBlogSliceDefaultPrimary>,
  Simplify<GrupoBlogSliceDefaultItem>
>;

/**
 * Slice variation for *GrupoBlog*
 */
type GrupoBlogSliceVariation = GrupoBlogSliceDefault;

/**
 * GrupoBlog Shared Slice
 *
 * - **API ID**: `grupo_blog`
 * - **Description**: GrupoBlog
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GrupoBlogSlice = prismic.SharedSlice<
  "grupo_blog",
  GrupoBlogSliceVariation
>;

/**
 * Primary content in *Mapa → Primary*
 */
export interface MapaSliceDefaultPrimary {
  /**
   * textomapa field in *Mapa → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mapa.primary.textomapa
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textomapa: prismic.KeyTextField;
}

/**
 * Primary content in *Mapa → Items*
 */
export interface MapaSliceDefaultItem {
  /**
   * cidade field in *Mapa → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mapa.items[].cidade
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cidade: prismic.KeyTextField;

  /**
   * estado field in *Mapa → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mapa.items[].estado
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  estado: prismic.KeyTextField;
}

/**
 * Default variation for Mapa Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MapaSliceDefaultPrimary>,
  Simplify<MapaSliceDefaultItem>
>;

/**
 * Slice variation for *Mapa*
 */
type MapaSliceVariation = MapaSliceDefault;

/**
 * Mapa Shared Slice
 *
 * - **API ID**: `mapa`
 * - **Description**: Mapa
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapaSlice = prismic.SharedSlice<"mapa", MapaSliceVariation>;

/**
 * Primary content in *Newsteller → Primary*
 */
export interface NewstellerSliceDefaultPrimary {
  /**
   * Titulo field in *Newsteller → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsteller.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Cor field in *Newsteller → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: newsteller.primary.cor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  cor: prismic.ColorField;

  /**
   * Ingles? field in *Newsteller → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: newsteller.primary.ingles
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  ingles: prismic.BooleanField;
}

/**
 * Default variation for Newsteller Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewstellerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewstellerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Newsteller*
 */
type NewstellerSliceVariation = NewstellerSliceDefault;

/**
 * Newsteller Shared Slice
 *
 * - **API ID**: `newsteller`
 * - **Description**: Newsteller
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewstellerSlice = prismic.SharedSlice<
  "newsteller",
  NewstellerSliceVariation
>;

/**
 * Primary content in *QuizSlice → Items*
 */
export interface QuizSliceSliceDefaultItem {
  /**
   * pergunta1 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].pergunta1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pergunta1: prismic.KeyTextField;

  /**
   * resposta1.1 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta11
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta11: prismic.KeyTextField;

  /**
   * resposta2.1 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta21
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta21: prismic.KeyTextField;

  /**
   * resposta3.1 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta31
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta31: prismic.KeyTextField;

  /**
   * pergunta2 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].pergunta2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pergunta2: prismic.KeyTextField;

  /**
   * resposta1.2 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta12
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta12: prismic.KeyTextField;

  /**
   * resposta2.2 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta22
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta22: prismic.KeyTextField;

  /**
   * resposta3.2 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta32
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta32: prismic.KeyTextField;

  /**
   * pergunta3 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].pergunta3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pergunta3: prismic.KeyTextField;

  /**
   * resposta1.3 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta13
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta13: prismic.KeyTextField;

  /**
   * resposta2.3 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta23
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta23: prismic.KeyTextField;

  /**
   * resposta3.3 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta33
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta33: prismic.KeyTextField;

  /**
   * pergunta4 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].pergunta4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pergunta4: prismic.KeyTextField;

  /**
   * resposta1.4 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta14
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta14: prismic.KeyTextField;

  /**
   * resposta2.4 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta24
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta24: prismic.KeyTextField;

  /**
   * resposta3.4 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta34
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta34: prismic.KeyTextField;

  /**
   * pergunta5 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].pergunta5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pergunta5: prismic.KeyTextField;

  /**
   * resposta1.5 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta15
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta15: prismic.KeyTextField;

  /**
   * resposta2.5 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta25
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta25: prismic.KeyTextField;

  /**
   * resposta3.5 field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resposta35
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta35: prismic.KeyTextField;

  /**
   * resultado Maioria A field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resultadoMaioriaA
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resultadoMaioriaA: prismic.KeyTextField;

  /**
   * resultado Maioria B field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resultadoMaioriaB
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resultadoMaioriaB: prismic.KeyTextField;

  /**
   * resultado Maioria C field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].resultadoMaioriaC
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resultadoMaioriaC: prismic.KeyTextField;

  /**
   * textoBotao field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].textobotao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textobotao: prismic.KeyTextField;

  /**
   * textoResultado field in *QuizSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_slice.items[].textoresultado
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textoresultado: prismic.KeyTextField;
}

/**
 * Default variation for QuizSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuizSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<QuizSliceSliceDefaultItem>
>;

/**
 * Slice variation for *QuizSlice*
 */
type QuizSliceSliceVariation = QuizSliceSliceDefault;

/**
 * QuizSlice Shared Slice
 *
 * - **API ID**: `quiz_slice`
 * - **Description**: QuizSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuizSliceSlice = prismic.SharedSlice<
  "quiz_slice",
  QuizSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataHeaderItem,
      BlogDocumentDataRodapeItem,
      BlogDocumentDataSlicesSlice,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataHeaderItem,
      BlogPostDocumentDataSlicesSlice,
      FaqpageDocument,
      FaqpageDocumentData,
      FaqpageDocumentDataHeaderItem,
      FaqpageDocumentDataRodapemenuItem,
      FaqpageDocumentDataRodapeconteudosItem,
      FaqpageDocumentDataSlicesSlice,
      IndexDocument,
      IndexDocumentData,
      IndexDocumentDataSlicesSlice,
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataHeaderItem,
      LandingPageDocumentDataBannerItem,
      LandingPageDocumentDataRodapemenuItem,
      LandingPageDocumentDataRodapeconteudosItem,
      LandingPageDocumentDataSlicesSlice,
      QuizDocument,
      QuizDocumentData,
      QuizDocumentDataHeaderItem,
      QuizDocumentDataRodapemenuItem,
      QuizDocumentDataRodapeconteudosItem,
      QuizDocumentDataSlicesSlice,
      SurveyDocument,
      SurveyDocumentData,
      SurveyDocumentDataSlicesSlice,
      TesteDocument,
      TesteDocumentData,
      TesteDocumentDataSlicesSlice,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      BlogConteudoSlice,
      BlogConteudoSliceDefaultPrimary,
      BlogConteudoSliceImagemPrimary,
      BlogConteudoSliceIFramePrimary,
      BlogConteudoSliceVariation,
      BlogConteudoSliceDefault,
      BlogConteudoSliceImagem,
      BlogConteudoSliceIFrame,
      CorpoSlice,
      CorpoSliceDefaultItem,
      CorpoSliceImagensItem,
      CorpoSliceIFrameItem,
      CorpoSliceLogosItem,
      CorpoSliceDepoimentosItem,
      CorpoSliceGatilhossociaisItem,
      CorpoSliceAgendaItem,
      CorpoSliceBotaoQuizItem,
      CorpoSliceVariation,
      CorpoSliceDefault,
      CorpoSliceImagens,
      CorpoSliceIFrame,
      CorpoSliceLogos,
      CorpoSliceDepoimentos,
      CorpoSliceGatilhossociais,
      CorpoSliceAgenda,
      CorpoSliceMapa,
      CorpoSliceBotaoQuiz,
      EmAltaSlice,
      EmAltaSliceDefaultPrimary,
      EmAltaSliceDefaultItem,
      EmAltaSliceVariation,
      EmAltaSliceDefault,
      FaqSlice,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      FaqSliceTitulo,
      FormularioSlice,
      FormularioSliceDefaultPrimary,
      FormularioSliceVariation,
      FormularioSliceDefault,
      GrupoBlogSlice,
      GrupoBlogSliceDefaultPrimary,
      GrupoBlogSliceDefaultItem,
      GrupoBlogSliceVariation,
      GrupoBlogSliceDefault,
      MapaSlice,
      MapaSliceDefaultPrimary,
      MapaSliceDefaultItem,
      MapaSliceVariation,
      MapaSliceDefault,
      NewstellerSlice,
      NewstellerSliceDefaultPrimary,
      NewstellerSliceVariation,
      NewstellerSliceDefault,
      QuizSliceSlice,
      QuizSliceSliceDefaultItem,
      QuizSliceSliceVariation,
      QuizSliceSliceDefault,
    };
  }
}
