// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_conteudo: dynamic(() => import("./BlogConteudo")),
  corpo: dynamic(() => import("./Corpo")),
  em_alta: dynamic(() => import("./EmAlta")),
  formulario: dynamic(() => import("./Formulario")),
  grupo_blog: dynamic(() => import("./GrupoBlog")),
  newsteller: dynamic(() => import("./Newsteller")),
};
