import Head from 'next/head'
import Styles from "./style.module.scss"
import Header from "../components/header"
import Banner from "../components/banner"
import Corpo from "../components/corpo"
import { Inter } from 'next/font/google'
import Formulario from '../components/formulario'
import Rodape from '../components/rodape'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>IndHUGE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*adicionar alalytics*/}
      <div className={Styles.container}>
        <Header className={Styles.header}/>
        <Banner className={Styles.banner}/>
        <Corpo className={Styles.corpo}/>
        <Formulario className={Styles.corpo}/>
        <Rodape className={Styles.rodape}/>
      </div>
    </>
  )
}