import Head from 'next/head'
import Styles from "./style.module.scss"
import Header from "../components/header"
import Banner from "../components/banner"
import Corpo from "../components/corpo"
import { Inter } from 'next/font/google'
import Formulario from '../components/formulario'
import Rodape from '../components/rodape'
import { useEffect } from "react";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

/*conexão com o servidor do chatbot*/
  useEffect(() => {
    window.botpressWebChat.init({
      composerPlaceholder: "Chat with IndHelp",
      botConversationDescription: "Tire suas duvidas",
      botId: "a65625bb-64c9-4a57-b4db-a7bd2aa1270b",
      hostUrl: "https://cdn.botpress.cloud/webchat/v0",
      messagingUrl: "https://messaging.botpress.cloud",
      clientId: "a65625bb-64c9-4a57-b4db-a7bd2aa1270b",
      botName: "IndHelp",
    });
  });

  return (
    <>
      <Head>
        <title>IndHUGE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Styles.container}>
        <Header className={Styles.header}/>
        <Banner className={Styles.banner}/>
        <Corpo className={Styles.corpo}/>
        <Formulario className={Styles.corpo}/>
        <Rodape className={Styles.rodape}/>
      </div>
      <script src="https://cdn.botpress.cloud/webchat/v0/inject.js"></script>
    </>
  )
}